# This is a basic workflow to help you get started with Actions

name: Demo - CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout to GitHub workspace
        uses: actions/checkout@v4

      - name: Step 2 - Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 17
          distribution: temurin
    
      # Builds/Executes Maven project, omits logs on dependency download progress
      - name: Step 2 - Build/Execute Tests
        run: mvn -B clean verify --no-transfer-progress

      - name: Generate Allure Report
        uses: allure-framework/allure-action@v0
        with:
          allure-results: allure-results
          allure-report: allure-report

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: allure-report
          # A file, directory or wildcard pattern that describes what to upload.
          path: allure-report
